// Importa os pacotes
const Database = require('./db');
const savequadra = require('./savequadra');

Database.then(async db => {
    // Inserir dados na tabela
    await savequadra(db, 
        {
            lat: "-23.4998459",
            lng: "-46.5775701",
            name: "SilverGold",
            type_block: "Vôlei",
            about: "1 quadra mede 18 metros de comprimento e 9 metros de largura, Quadra Coberta, Vestiário: Feminino e Masculino com chuveiro, Lanchonete/bar, Churrasqueira",
            images: [
                "https://i.ibb.co/98zt9rn/Quadra1-Volei.png",
                "https://i.ibb.co/FYQs9PS/Quadra1-Volei-5.png",
                "https://i.ibb.co/NstqrfT/Quadra1-Volei-4.png",
                "https://i.ibb.co/h2C1rj8/Quadra1-Volei-3.png",
                "https://i.ibb.co/FzK6QjD/Quadra1-Volei-2.png",
            ].toString(),
            cep: "02134-050",
            street: "Praça Yedo",
            number: 136,
            district: "Vila Maria Alta",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "11 94774-5871",
            telephone: "11 2201-4835",
            email: "contato@silvergold.com.br",
            opening_hours: "2 horas",
            price_hour: "R$ 200,00",
            open_on_weekends: "Sim"
        });  await savequadra(db, 
        {
            lat: "-23.5049271",
            lng: "-47.5129156",
            name: "JMF",
            type_block: "Vôlei",
            about: "1 quadra, quadra Coberta, vestiário: Feminino e Masculino com chuveiro, Lanchonete/bar, Churrasqueira",
            images: [
                "https://i.ibb.co/FXsd1Fk/Quadra2-Volei-2.png",
                "https://i.ibb.co/WBkTXMy/Quadra2-Volei-3.png",
                "https://i.ibb.co/WgsfVms/Quadra2-Volei-4.png",
                "https://i.ibb.co/wdjPhb7/Quadra2-Volei.png",
            ].toString(),
            cep: "18056-500",
            street: "Rua Abner Pacheco",
            number: 260,
            district: "Júlio de Mesquita",
            city: "Sorocaba",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "15 3013-7672",
            email: "jmffutsal@hotmail.com",             
            opening_hours: "2 horas",
            price_hour: "R$ 220,00",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.7093665",
            lng: "-46.8543403",
            name: "DTenis",
            type_block: "Tênis",
            about: "4 Quadras Cobertas de dimensões oficiais e piso com sistema profissional de amortecimento altamente eficiente, que garante mais segurança esportiva, Estacionamento - Gratuito, Vestiário: Feminino e Masculino com chuveiro, Arquibancada, Acessibilidade para pessoas com mobilidade reduzida, Lanchonete.",
            images: [
                "https://i.ibb.co/6sSPtrF/Quadra1-Tenis-2.png",
                "https://i.ibb.co/mtNv9V1/Quadra1-Tenis-3.png",
                "https://i.ibb.co/3W0PX9k/Quadra1-Tenis-4.png",
                "https://i.ibb.co/kDzsvND/Quadra1-Tenis-5.png",
                "https://i.ibb.co/JqJn1Qx/Quadra1-Tenis.png"
            ].toString(),
            cep: "06850-220",
            street: "Av. Belo Horizonte",
            number: 66,
            district: "Travessa da Av. XV de Novembro",
            city: "Itapecerica da Serra ",
            state: "São Paulo",
            whatsapp: "11 94767-8989",
            telephone: "11 4666-2431 ",
            email: "contato@dtenis.com.br",             
            opening_hours: "1 hora",
            price_hour: "R$ 100,00",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.578098",
            lng: "-46.638836",
            name: "PlayTennis",
            type_block: "Tênis",
            about: "3 quadras rápidas, 1 quadra de squash, Vestiário: Feminino e Masculino com chuveiro, Loja de materiais esportivos, Lanchonete",
            images: [
                "https://i.ibb.co/TWYq8TP/Quadra2-Tenis-2.png",
                "https://i.ibb.co/Csct0sq/Quadra2-Tenis-3.png",
                "https://i.ibb.co/8rC0C7w/Quadra2-Tenis-4.png",
                "https://i.ibb.co/4mwY4n0/Quadra2-Tenis-5.png",
                "https://i.ibb.co/7QLFD9X/Quadra2-Tenis.png",
            ].toString(),
            cep: "04103-030",
            street: "Av. Armando Ferrentini",
            number: 671,
            district: "Aclimação",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "11 97100-5727",
            telephone: "11 3207-2107",
            email: "playaclimacao@playtennis.com.br",             
            opening_hours: "1 hora",
            price_hour: "R$ 110,00",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.5602467",
            lng: "-46.6180355",
            name: "Open Quadra de Tênis",
            type_block: "Tênis",
            about: "2 quadras de saibro, Vestiário: Feminino e Masculino com chuveiro, Lanchonete",
            images: [
                "https://i.ibb.co/wp81mQ3/Quadra3-Tenis.png",
                "https://i.ibb.co/hg99fHy/Quadra3-Tenis-5.png",
                "https://i.ibb.co/s9nt30M/Quadra3-Tenis-4.png",
                "https://i.ibb.co/T4vfpT8/Quadra3-Tenis-3.png",
                "https://i.ibb.co/5T0p2PT/Quadra3-Tenis-2.png",
            ].toString(),
            cep: "03340-000",
            street: "Rua Ana Neri",
            number: 697,
            district: "Cambuci",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "11 3208-1848",
            email: "open@openquadradetenis.com.br",             
            opening_hours: "1 hora",
            price_hour: "R$ 120,00",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.5981849",
            lng: "-46.5830425",
            name: "Arena Sport Brasil",
            type_block: "Handebol",
            about: "1 Quadra, Quadra Coberta, Vestiário: Masculino e Feminino com chuveiro, Lanchonete, churrasqueira",
            images: [
                "https://uploaddeimagens.com.br/images/003/216/041/full/Quadra1_Handebol_%282%29.png?1619567633",
                "https://uploaddeimagens.com.br/images/003/216/043/full/Quadra1_Handebol_%283%29.png?1619567680",
                "https://uploaddeimagens.com.br/images/003/216/045/full/Quadra1_Handebol.png?1619567700",
            ].toString(),
            cep: "03153-002",
            street: "Avenida Doutor Francisco Mesquita",
            number: 1750,
            district: "-",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "11 2272-0248",
            email: "contato@arenasportbrasil.com.br",             
            opening_hours: "1 hora",
            price_hour: "R$ 150,00",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.4598537",
            lng: "-46.589647",
            name: "A.A. Guapira",
            type_block: "Handebol",
            about: "3 Quadras, Quadra Coberta, Vestiário: Masculino e Feminino com chuveiro, Lanchonete",
            images: [
                "https://uploaddeimagens.com.br/images/003/216/046/full/Quadra2_Handebol.png?1619567773",
                "https://i.ibb.co/84FyLqz/Quadra2-Handebol-2.png",
            ].toString(),
            cep: "02317-180",
            street: "Rua Dr. José Camargo Aranha",
            number: 376,
            district: "Jardim Guapira",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "11 2249-9102",
            email: "secretaria@clubeguapira.com.br",             
            opening_hours: "2 horas",
            price_hour: "R$ 150,00",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.5859921",
            lng: "-46.6571085",
            name: "Quadra 1 gratuita",
            type_block: "Gratuita",
            about: "1 Quadra - Handebol, Basquete, Vôlei, Quadra aberta, Vestiário: Masculino e Feminino publico, Wi-Fi Publico, Estacionamento" ,
            images: [
                "https://i.ibb.co/Mp44Sp6/Quadra1-Gratuita-2.png",
                "https://i.ibb.co/CtVj8r4/Quadra1-Gratuita-3.png",
                "https://i.ibb.co/ydZwWKT/Quadra1-Gratuita.png",
            ].toString(),
            cep: "04094-050",
            street: "Av. Pedro Álvares Cabral",
            number: null,
            district: "Vila Mariana",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "11 5574-5045",
            email: "Sem e-mail",             
            opening_hours: "05:00 – 00:00",
            price_hour: "Gratuito",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.4951764",
            lng: "-46.5057176",
            name: "Quadra 2 gratuita",
            type_block: "Gratuita",
            about: "1 Quadra - Handebol, Basquete, Vôlei, Quadra aberta, Vestiário: Masculino e Feminino publico, Wi-Fi Publico, Estacionamento" ,
            images: [
                "https://i.ibb.co/7RkgxtD/Quadra2-Gratuita-2.png",
                "https://i.ibb.co/txzBdXS/Quadra2-Gratuita-3.png",
                "https://i.ibb.co/5Tvmr2W/Quadra2-Gratuita-4.png",
                "https://i.ibb.co/MkqsRCj/Quadra2-Gratuita.png",
            ].toString(),
            cep: "03820-100",
            street: "Rua Carlos Barbosa",
            number: 365,
            district: "Cangaíba",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "Sem telefone",
            email: "Sem e-mail",             
            opening_hours: "06:00 – 18:00",
            price_hour: "Gratuito",
            open_on_weekends: "Sim"
        }); await savequadra(db, 
        {
            lat: "-23.5014681",
            lng: "-46.7386106",
            name: "Quadra 3 gratuita",
            type_block: "Gratuita",
            about: "1 Quadra - Handebol, Basquete, Vôlei, Quadra aberta, Lanchonete/bar, Estacionamento" ,
            images: [
                "https://i.ibb.co/RgQvcWf/Quadra3-Gratuita-2.png",
                "https://i.ibb.co/sHyK9df/Quadra3-Gratuita.png",
            ].toString(),
            cep: "05124-050",
            street: "Rua Pedro Sernagiotti",
            number: 125,
            district: "Pirituba",
            city: "São Paulo",
            state: "São Paulo",
            whatsapp: "Sem whatsapp",
            telephone: "11 5574-5045",
            email: "Sem e-mail",             
            opening_hours: "05:00 – 00:00",
            price_hour: "Gratuito",
            open_on_weekends: "Sim"
        }
    );

    // Consultar dados da tabela
    // const selectedquadras = await db.all('SELECT * FROM quadras');
    // console.log(selectedquadras);

    // Consultar somente um orfanato pelo id
    // const quadra = await db.all('SELECT * FROM quadras WHERE id = "1"');
    // console.log(quadra);

    // Deletar dados da tabela
    // console.log(await db.run('DELETE FROM quadras WHERE id = "1"'));
});